# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Attempt build
run-name: PR build check

# Checks if a pull request builds properly on windows and linux, uploads artifacts of those builds.

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  WINDOWS_BUILD_NAME: CyberpunkModManager-Windows-${{ github.run_number }}
  LINUX_BUILD_NAME: CyberpunkModManager-Linux-${{ github.run_number }}

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup VS devenv for amd64
      uses: seanmiddleditch/gha-setup-vsdevenv@master
      with:
        arch: amd64

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Run Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./Setup.ps1 CI_BUILD

    - name: Build Application
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild CyberpunkModManager.sln /p:Configuration=Release

    - name: Make release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cd App && ./MakeRelease.ps1

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: App/Release
        name: ${{env.WINDOWS_BUILD_NAME}}


  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Init submodules
      run: git submodule update --init --recursive
    
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt autoremove --purge snapd
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libglew-dev

    - name: Build Application
      run: |
        cd App/
        cmake -S . -B Build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build Build/ -j 8
    - name: Make release
      run: |
        cd App/
        mkdir Release/
        cp -rf app/ Release/app/
        cp ../LICENSE.txt Release/
        cp Build/App Release/CyberpunkModManager

    - name: Upload release artifact
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: App/Release
        name: ${{env.LINUX_BUILD_NAME}}
