# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Attempt build
run-name: PR build check

# Checks if a pull request builds properly on windows and linux, uploads artifacts of those builds.

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  WINDOWS_BUILD_NAME: CyberpunkModManager-Windows-${{ github.run_number }}
  LINUX_BUILD_NAME: CyberpunkModManager-Linux-${{ github.run_number }}

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt autoremove --purge snapd
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libglew-dev

    - name: Build Application
      run: |
        cmake -S . -B Build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build Build/ -j 8
    - name: Make release
      run: |
        mkdir Release/
        cp -rf App/app/ Release/app/
        cp LICENSE.txt Release/
        cp Build/ModManager Release/CyberpunkModManager

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: Release
        name: ${{env.LINUX_BUILD_NAME}}
